apiVersion: v1
kind: Service
metadata:
  name: mariadb-inventory
  namespace: polyglot
spec:
  clusterIP: None
  selector:
    app: mariadb-inventory
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-inventory
  namespace: polyglot
spec:
  serviceName: mariadb-inventory
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-inventory
  template:
    metadata:
      labels:
        app: mariadb-inventory
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.2
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: DB_NAME_INVENTORY
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: DB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: DB_PASSWORD
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: MARIADB_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi